server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://wanyakun:123.com@peer1:8761/eureka/, http://wanyakun:123.com@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enable: true
  compression:
    response:
      enable: true
    request:
      enable: true
      min-request-size: 2048
logging:
  level:
    com.aioser.cloud.study.microserviceconsumermovie.user.feign.UserFeignClient: DEBUG

